### Site metadata ###

title: My GitHub Projects

repository: mkeeves/mkeeves.github.io
author: Mike Keeves

### Build settings ###

url: mkeeves.github.io
baseurl: ""

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

remote_theme: pages-themes/slate@v0.2.0

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

