### Site metadata ###

title: mkeeves.com
tagline: "IT Professional & Technology Enthusiast"
description: "Personal blog of Mike Keeves - IT professional sharing insights on PowerShell, Microsoft technologies, and system administration."

repository: mkeeves/mkeeves.github.io
author: Mike Keeves
logo: "/_images/logo1.jpg"

# Site navigation
navigation:
  - title: "Home"
    url: /
  - title: "Posts"
    url: /posts/
  - title: "QR Generator"
    url: https://qr.mkeeves.com
    external: true

# Social links removed per user request

copyright: "© 2024 Mike Keeves"

# Custom styling - no theme dependencies
# All styling is handled inline in HTML files

### Build settings ###

#url: mkeeves.github.io

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# No remote theme - using custom styling
#remote_theme: pages-themes/slate@v0.2.0
#remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-paginate

# Pagination
paginate: 5
paginate_path: "/posts/page:num/"

# SEO
seo:
  type: "Person"
  name: "Mike Keeves"

