### Site metadata ###

title: my website

repository: mkeeves/mkeeves.github.io
author: Mike Keeves

#footer_links:
#  - title: Twitter
#    url: https://twitter.com/username
#    icon: fab fa-twitter-square
#  - title: GitHub
#    url: https://github.com/
#    icon: fab fa-github-square
#  - title: Feed
#    url: atom.xml
#    icon: fas fa-rss-square

copyright: "This site is made with <3 by *me, myself, and I*."

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

### Build settings ###

#url: mkeeves.github.io
#baseurl: ""

collections:
  authors:
    output: true

#defaults:
#  - scope:
#      path: ""
#      type: "authors"
#    values:
#      layout: "author"
#  - scope:
#      path: ""
#      type: "posts"
#    values:
#      layout: "post"
#  - scope:
#      path: ""
#    values:
#      layout: "default"

remote_theme: pages-themes/slate@v0.2.0
#remote_theme: "mmistakes/so-simple-theme@3.2.0"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-include-cache

