### Site metadata ###

title: mkeeves.com
tagline: "IT Professional & Technology Enthusiast"
description: "Personal blog of Mike Keeves - IT professional sharing insights on PowerShell, Microsoft technologies, and system administration."

repository: mkeeves/mkeeves.github.io
author: Mike Keeves
logo: "/_images/logo1.jpg"

# Site navigation
navigation:
  - title: "Home"
    url: /
  - title: "Posts"
    url: /posts/
  - title: "QR Generator"
    url: https://qr.mkeeves.com
    external: true

# Social links removed per user request

copyright: "© 2024 Mike Keeves"

# Chirpy theme settings
theme_mode:
  light: "light"
  dark: "dark"
  auto: "auto"

# Custom assets
custom_css:
  - assets/css/custom.scss

custom_js:
  - assets/js/theme-toggle.js

# Font settings
font:
  text: "Inter"
  code: "JetBrains Mono"

google_fonts:
  - name: "Inter"
    weights: "300,400,500,600,700"
  - name: "JetBrains Mono"
    weights: "400,500,700"

### Build settings ###

#url: mkeeves.github.io

collections:
  authors:
    output: true

#defaults:
#  - scope:
#      path: ""
#      type: "authors"
#    values:
#      layout: "author"
#  - scope:
#      path: ""
#      type: "posts"
#    values:
#      layout: "post"
#  - scope:
#      path: ""
#    values:
#      layout: "default"

#remote_theme: pages-themes/slate@v0.2.0
remote_theme: "cotes2020/jekyll-theme-chirpy@6.2.3"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-scholar
  - jekyll-redirect-from
  - jekyll-archives

# Pagination
paginate: 5
paginate_path: "/posts/page:num/"

# SEO
seo:
  type: "Person"
  name: "Mike Keeves"

